CREATE TABLE YeuCauTraHang (
    MaYeuCauTraHang INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaDonHang INT UNSIGNED NOT NULL,
    MaNguoiYeuCau INT UNSIGNED NOT NULL,
    LyDo VARCHAR(500) NOT NULL,
    TrangThai ENUM('CHO_DUYET','DA_DUYET','DA_NHAN_HANG','TU_CHOI','DA_HOAN_TIEN') NOT NULL DEFAULT 'CHO_DUYET',
    GhiChuXuLy VARCHAR(500),
    MaNguoiXuLy INT UNSIGNED,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NgayNhanHang DATETIME NULL,
    NgayHoanTien DATETIME NULL,
    CONSTRAINT FK_YeuCauTraHang_DonHang FOREIGN KEY (MaDonHang)
        REFERENCES DonHang(MaDonHang) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_YeuCauTraHang_NguoiYeuCau FOREIGN KEY (MaNguoiYeuCau)
        REFERENCES NguoiDung(MaNguoiDung) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_YeuCauTraHang_NguoiXuLy FOREIGN KEY (MaNguoiXuLy)
        REFERENCES NguoiDung(MaNguoiDung) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX IX_YeuCauTraHang_DonHang (MaDonHang, NgayTao),
    INDEX IX_YeuCauTraHang_TrangThai (TrangThai, NgayTao)
) ENGINE=InnoDB;
