import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import './product.css'
import './gallery.css'
import CatalogAdminScreen from './CatalogAdminScreen'
import { ImageAdminScreen, VariantAdminScreen } from './ProductResourceScreens'

type Product = Record<string, any>
type CatalogType = 'categories' | 'brands' | 'colors' | 'sizes'
const API = import.meta.env.VITE_API_URL || 'http://localhost:7000'
const headers = () => ({ 'Content-Type': 'application/json', ...(localStorage.getItem('admin_token') ? { Authorization: `Bearer ${localStorage.getItem('admin_token')}` } : {}) })
const demo: Product[] = []
export default function ProductManagement({ mode }: { mode: string }) { if (mode === 'products') return <ProductList />; if (mode === 'variants') return <VariantAdminScreen />; if (mode === 'images') return <ImageAdminScreen />; return <CatalogAdminScreen type={mode as CatalogType} /> }


function ProductList() { const [rows, setRows] = useState<Product[]>(demo); const [query, setQuery] = useState(''); const [showForm, setShowForm] = useState(false); useEffect(() => { fetch(`${API}/api/admin/products`, { headers: headers() }).then((res) => res.ok ? res.json() : null).then((body) => body?.data?.length && setRows(body.data)).catch(() => undefined) }, []); const filtered = rows.filter((row) => `${row.TenSanPham} ${row.MaSanPhamCode}`.toLowerCase().includes(query.toLowerCase())); return <Shell eyebrow="SẢN PHẨM / DANH SÁCH SẢN PHẨM" title="Quản lý sản phẩm" description="Theo dõi danh mục thời trang, biến thể SKU, giá niêm yết và lượng hàng khả dụng." actions={<><button className="outline-action">⇩ Xuất Excel</button><button className="primary-action" onClick={() => setShowForm(true)}>⊕ Thêm sản phẩm</button></>}><div className="product-metrics"><Metric title="Tổng sản phẩm" value={rows.length} note="mã cha" tone="blue" /><Metric title="Đang kinh doanh" value={rows.filter((row) => row.TrangThai !== 'NGUNG_BAN').length} note="dang b�n" tone="green" /><Metric title="Hết hàng / tạm ngừng" value={rows.filter((row) => ['HET_HANG', 'NGUNG_BAN'].includes(String(row.TrangThai))).length} note="h?t h�ng" tone="red" /><Metric title="Cần cập nhật ảnh/giá" value="14" note="cần duyệt" tone="orange" /></div><div className="filter-panel"><div className="product-search">⌕ <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm kiếm theo tên sản phẩm hoặc mã SKU..." /></div><select><option>Tất cả danh mục</option></select><select><option>Tất cả thương hiệu</option></select><select><option>Tất cả trạng thái</option></select><label><input type="checkbox" defaultChecked /> Sản phẩm mới</label><label><input type="checkbox" /> Nổi bật</label></div><div className="bulk-bar">☑ Đã chọn 3 sản phẩm <span>Áp dụng hành động cho các biến thể SKU liên quan</span><button>Đang bán</button><button>Ngừng bán</button><button className="danger-action">Xóa đã chọn</button></div><div className="table-card"><table className="admin-table"><thead><tr><th>Ảnh</th><th>Tên sản phẩm</th><th>SKU / Biến thể</th><th>Danh mục</th><th>Thương hiệu</th><th>Giá bán</th><th>Trạng thái</th></tr></thead><tbody>{filtered.map((row) => <tr key={String(row.MaSanPham)}><td><div className="product-thumb">FS</div></td><td><strong>{String(row.TenSanPham)}</strong><small>Mã #{row.MaSanPham}</small></td><td><b className="sku">{String(row.MaSanPhamCode)}</b><small>4 Màu · 4 Size</small></td><td><span className="tag">{String(row.TenDanhMuc)}</span></td><td>{String(row.TenThuongHieu)}</td><td><strong>{Number(row.GiaBan).toLocaleString('vi-VN')} đ</strong></td><td><span className="status-pill">● Đang bán</span></td></tr>)}</tbody></table></div>{showForm && <ProductForm onClose={() => setShowForm(false)} onSaved={(row) => { setRows((current) => [row, ...current]); setShowForm(false) }} />}</Shell> }

function ProductForm({ onClose, onSaved }: { onClose: () => void; onSaved: (row: Product) => void }) { async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const payload = { ...values, GiaBan: Number(values.GiaBan), GiaNhap: Number(values.GiaNhap), NoiBat: values.NoiBat ? 1 : 0 }; const response = await fetch(`${API}/api/admin/products`, { method: 'POST', headers: headers(), body: JSON.stringify(payload) }); if (response.ok) { const body = await response.json(); onSaved({ ...payload, MaSanPham: body.insertId }) } } return <div className="modal-backdrop"><form className="modal-form" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}>×</button><h2>Thêm sản phẩm mới</h2><p>Tạo bản ghi theo bảng SanPham.</p><label>Mã sản phẩm<input name="MaSanPhamCode" required placeholder="FS-PL-020" /></label><label>Tên sản phẩm<input name="TenSanPham" required placeholder="Tên sản phẩm" /></label><div className="form-row"><label>Mã danh mục<input name="MaDanhMuc" required /></label><label>Mã thương hiệu<input name="MaThuongHieu" /></label></div><div className="form-row"><label>Giá bán<input name="GiaBan" type="number" defaultValue="0" /></label><label>Giá nhập<input name="GiaNhap" type="number" defaultValue="0" /></label></div><label>Trạng thái<select name="TrangThai" defaultValue="DANG_BAN"><option value="DANG_BAN">ĐANG BÁN</option><option value="NGUNG_BAN">NGỪNG BÁN</option><option value="HET_HANG">HẾT HÀNG</option></select></label><button className="primary-action">Lưu sản phẩm</button></form></div> }

function Shell({ eyebrow, title, description, actions, children }: { eyebrow: string; title: string; description: string; actions?: ReactNode; children: ReactNode }) { return <section className="product-page"><div className="product-heading"><div><small>{eyebrow}</small><h1>{title}</h1><p>{description}</p></div><div>{actions}</div></div>{children}</section> }
function Metric({ title, value, note, tone }: { title: string; value: string | number; note: string; tone: string }) { return <article className={`metric ${tone}`}><div><span>{title}</span><b>▣</b></div><strong>{value}</strong><small>{note}</small></article> }
