import { useEffect, useState } from 'react'
import './product.css'

type Row = Record<string, unknown>
const API = import.meta.env.VITE_API_URL || 'http://localhost:7000'
const headers = () => ({ 'Content-Type': 'application/json', ...(localStorage.getItem('admin_token') ? { Authorization: `Bearer ${localStorage.getItem('admin_token')}` } : {}) })
const loadJson = (url: string) => fetch(url, { headers: headers() }).then((response) => response.ok ? response.json() : null)

export function VariantAdminScreen() {
  const [products, setProducts] = useState<Row[]>([]); const [productId, setProductId] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [form, setForm] = useState({ SKU: '', MaMauSac: '', MaKichThuoc: '', GiaBan: '0', GiaNhap: '0', SoLuongTon: '0' })
  useEffect(() => { void loadJson(`${API}/api/admin/products`).then((body) => { const items = Array.isArray(body?.data) ? body.data : []; setProducts(items); if (items[0]) setProductId(String(items[0].MaSanPham)) }) }, [])
  useEffect(() => { if (productId) void loadJson(`${API}/api/admin/products/${productId}/variants`).then((body) => setRows(Array.isArray(body?.data) ? body.data : [])) }, [productId])
  const create = async () => { if (!productId || !form.SKU) return; const response = await fetch(`${API}/api/admin/products/${productId}/variants`, { method: 'POST', headers: headers(), body: JSON.stringify({ ...form, MaSanPham: Number(productId), MaMauSac: Number(form.MaMauSac) || null, MaKichThuoc: Number(form.MaKichThuoc) || null, GiaBan: Number(form.GiaBan), GiaNhap: Number(form.GiaNhap), SoLuongTon: Number(form.SoLuongTon) }) }); if (response.ok) { setForm({ SKU: '', MaMauSac: '', MaKichThuoc: '', GiaBan: '0', GiaNhap: '0', SoLuongTon: '0' }); const body = await loadJson(`${API}/api/admin/products/${productId}/variants`); setRows(body?.data || []) } }
  return <ResourceShell title="Biến thể sản phẩm"><label>Sản phẩm<select value={productId} onChange={(event) => setProductId(event.target.value)}>{products.map((product) => <option key={String(product.MaSanPham)} value={String(product.MaSanPham)}>{String(product.TenSanPham)} · #{String(product.MaSanPham)}</option>)}</select></label><div className="form-row"><input value={form.SKU} onChange={(event) => setForm({ ...form, SKU: event.target.value })} placeholder="SKU" /><input value={form.MaMauSac} onChange={(event) => setForm({ ...form, MaMauSac: event.target.value })} placeholder="Mã màu" /><input value={form.MaKichThuoc} onChange={(event) => setForm({ ...form, MaKichThuoc: event.target.value })} placeholder="Mã kích thước" /><input value={form.GiaBan} onChange={(event) => setForm({ ...form, GiaBan: event.target.value })} placeholder="Giá bán" type="number" /><button className="primary-action" onClick={() => void create()}>Thêm biến thể</button></div><table className="admin-table"><thead><tr><th>SKU</th><th>Màu</th><th>Kích thước</th><th>Giá bán</th><th>Tồn kho</th><th>Trạng thái</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.MaBienThe)}><td>{String(row.SKU)}</td><td>{String(row.TenMau || row.MaMauSac || '-')}</td><td>{String(row.TenKichThuoc || row.MaKichThuoc || '-')}</td><td>{Number(row.GiaBan || 0).toLocaleString('vi-VN')} đ</td><td>{String(row.SoLuongTon || 0)}</td><td>{String(row.TrangThai || '-')}</td></tr>)}</tbody></table></ResourceShell>
}

export function ImageAdminScreen() {
  const [products, setProducts] = useState<Row[]>([]); const [productId, setProductId] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [url, setUrl] = useState('')
  useEffect(() => { void loadJson(`${API}/api/admin/products`).then((body) => { const items = Array.isArray(body?.data) ? body.data : []; setProducts(items); if (items[0]) setProductId(String(items[0].MaSanPham)) }) }, [])
  const load = () => productId && loadJson(`${API}/api/admin/products/${productId}/images`).then((body) => setRows(Array.isArray(body?.data) ? body.data : []))
  useEffect(() => { void load() }, [productId])
  const add = async () => { if (!productId || !url.trim()) return; const response = await fetch(`${API}/api/admin/products/${productId}/images`, { method: 'POST', headers: headers(), body: JSON.stringify({ DuongDanAnh: url, LaAnhChinh: rows.length ? 0 : 1, ThuTu: rows.length + 1 }) }); if (response.ok) { setUrl(''); await load() } }
  const remove = async (id: unknown) => { const response = await fetch(`${API}/api/admin/products/${productId}/images/${id}`, { method: 'DELETE', headers: headers() }); if (response.ok) await load() }
  return <ResourceShell title="Hình ảnh sản phẩm"><label>Sản phẩm<select value={productId} onChange={(event) => setProductId(event.target.value)}>{products.map((product) => <option key={String(product.MaSanPham)} value={String(product.MaSanPham)}>{String(product.TenSanPham)} · #{String(product.MaSanPham)}</option>)}</select></label><div className="form-row"><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="URL hình ảnh" /><button className="primary-action" onClick={() => void add()}>Thêm ảnh</button></div><div className="image-library">{rows.map((row) => <article className="image-card" key={String(row.MaHinhAnh)}><img src={String(row.DuongDanAnh)} alt={String(row.MoTa || '')} /><small>{Number(row.LaAnhChinh) === 1 ? 'Ảnh chính' : 'Ảnh phụ'}</small><button className="table-action" onClick={() => void remove(row.MaHinhAnh)}>Xóa</button></article>)}</div></ResourceShell>
}

function ResourceShell({ title, children }: { title: string; children: React.ReactNode }) { return <section className="product-page"><div className="product-heading"><div><small>SẢN PHẨM / {title.toUpperCase()}</small><h1>Quản lý {title.toLowerCase()}</h1><p>CRUD trực tiếp theo schema và API quản trị tương ứng.</p></div></div><div className="table-card catalog-table">{children}</div></section> }
