import { useEffect, useMemo, useState } from 'react'
import './ProductScreens.css'

type ProductScreenProps = { active: string }
type Product = { id: number; code: string; name: string; category: string; brand: string; price: number; stock: number; variants: number; status: string; tag: string }
const API = import.meta.env.VITE_API_URL || 'http://localhost:7000'
const demoProducts: Product[] = [
  { id: 1, code: 'FS-BL-042', name: 'Áo Blazer Unisex Hàn Quốc Form Rộng', category: 'Áo khoác', brand: 'FashionStore Signature', price: 650000, stock: 42, variants: 20, status: 'Đang bán', tag: 'Hot' },
  { id: 2, code: 'FS-DR-108', name: 'Đầm Hoa Nhí Vintage Freen Dáng Xòe', category: 'Váy đầm', brand: 'Elegant Seoul', price: 480000, stock: 28, variants: 12, status: 'Đang bán', tag: 'Nổi bật' },
  { id: 3, code: 'FS-PL-019', name: 'Áo Polo Nam Pique Cotton Co Giãn 4 Chiều', category: 'Áo thun & Polo', brand: 'FashionStore Basics', price: 299000, stock: 112, variants: 16, status: 'Đang bán', tag: 'Mới' },
]
const money = (value: number) => `${value.toLocaleString('vi-VN')} ₫`

export default function ProductScreens({ active }: ProductScreenProps) {
  if (!['Danh sách sản phẩm', 'Biến thể sản phẩm', 'Màu sắc', 'Kích thước', 'Danh mục', 'Thương hiệu', 'Hình ảnh sản phẩm'].includes(active)) return null
  if (active === 'Danh sách sản phẩm') return <ProductList />
  if (active === 'Biến thể sản phẩm') return <VariantPage />
  if (active === 'Màu sắc' || active === 'Kích thước') return <AttributePage active={active} />
  return <CatalogPage title={active} />
}

function ProductList() {
  const [products, setProducts] = useState(demoProducts)
  const [search, setSearch] = useState('')
  const [showForm, setShowForm] = useState(false)
  useEffect(() => { fetch(`${API}/api/admin/products`).then((response) => response.ok ? response.json() : Promise.reject()).then((body) => Array.isArray(body.data) && setProducts(body.data.map((item: any) => ({ ...demoProducts[0], id: item.MaSanPham, code: item.MaSanPhamCode || 'FS-SP', name: item.TenSanPham, category: item.TenDanhMuc || 'Chưa phân loại', brand: item.TenThuongHieu || 'Chưa cập nhật', price: Number(item.GiaBan || 0), stock: 0, variants: 0, status: item.TrangThai || 'Đang bán', tag: item.NoiBat ? 'Nổi bật' : '' })))).catch(() => undefined) }, [])
  const filtered = useMemo(() => products.filter((product) => `${product.name} ${product.code}`.toLowerCase().includes(search.toLowerCase())), [products, search])
  return <div className="product-screen"><div className="product-breadcrumb">SẢN PHẨM &nbsp;›&nbsp; DANH SÁCH SẢN PHẨM</div><div className="product-title"><div><h1>Quản lý sản phẩm</h1><p>Theo dõi danh mục thời trang, biến thể SKU, giá niêm yết và kiểm soát lượng hàng khả dụng trên toàn hệ thống.</p></div><div><button className="light-action">⇩ &nbsp; Xuất Excel</button><button className="primary-action" onClick={() => setShowForm(!showForm)}>⊕ &nbsp; Thêm sản phẩm</button></div></div>{showForm && <ProductForm onClose={() => setShowForm(false)} />}<div className="product-stats"><Stat label="TỔNG SẢN PHẨM" value="650" unit="mã cha" color="purple"/><Stat label="ĐANG KINH DOANH" value="582" unit="89.5%" color="green"/><Stat label="HẾT HÀNG / TẠM NGỪNG" value="68" unit="10.5%" color="red"/><Stat label="CẦN CẬP NHẬT ẢNH/GIÁ" value="14" unit="cần duyệt" color="orange"/></div><div className="product-filter"><label>⌕ <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm kiếm theo tên sản phẩm hoặc mã SKU..."/></label><button>Tất cả danh mục⌄</button><button>Tất cả thương hiệu⌄</button><button>Tất cả trạng thái⌄</button><div className="filter-options"><span>☑ &nbsp; Sản phẩm mới</span><span>□ &nbsp; Nổi bật (Featured)</span><span>☷ &nbsp; Bộ lọc nâng cao &nbsp;❷</span><span>↻ &nbsp; Đặt lại bộ lọc</span></div></div><div className="bulk-actions"><b>☑ &nbsp; Đã chọn 3 sản phẩm</b><span>Áp dụng hàng động từ chối cho toàn bộ biến thể SKU liên quan</span><button>◉ Đang bán</button><button>ⓘ Ngừng bán</button><button className="danger">▣ Xóa đã chọn</button></div><div className="product-table"><div className="table-head"><span>☑</span><span>HÌNH ẢNH</span><span>TÊN SẢN PHẨM</span><span>SKU / BIẾN THỂ</span><span>DANH MỤC</span><span>THƯƠNG HIỆU</span><span>GIÁ BÁN</span></div>{filtered.map((product) => <div className="product-row" key={product.id}><span>☑</span><div className="product-image">4 ảnh</div><div><strong>{product.name}</strong><small><b className="tag">{product.tag || 'Mới'}</b><br/>Tạo lúc: 14:20 28/10/2023 • Bởi Minh Đức</small></div><div><b className="sku">{product.code}</b><small>({product.variants} SKU)<br/>4 Màu • 5 Size</small></div><span className="pill">{product.category}</span><span>{product.brand}</span><strong className="price">{money(product.price)}<small>đ</small></strong></div>)}</div></div>
}

function ProductForm({ onClose }: { onClose: () => void }) { return <div className="product-form-screen"><div><div className="product-breadcrumb">← Quay lại danh sách / Sản phẩm / Thêm sản phẩm</div><h2>Thêm sản phẩm mới <small>• Bản nháp nội bộ</small></h2><p>Điền đầy đủ thông tin sản phẩm, quản lý thư viện hình ảnh và thiết lập biến thể màu sắc, kích cỡ.</p><div className="form-card"><h3>ⓘ &nbsp; Thông tin cơ bản <small>BẮT BUỘC</small></h3><label>Tên sản phẩm *<input defaultValue="Áo Polo Nam Pique Cotton Co Giãn 4 Chiều FashionStore Signature" /></label><div className="form-two"><label>Danh mục sản phẩm *<select><option>Áo thun & Polo</option></select></label><label>Thương hiệu thời trang *<select><option>FashionStore Signature</option></select></label></div><label>Mô tả sản phẩm<textarea defaultValue="Dòng áo Polo cao cấp ứng dụng kỹ thuật dệt Pique Cotton 95% sợi thiên nhiên kết hợp 5% Spandex siêu co giãn, thoáng khí tối đa." /></label><div className="price-box"><label>Giá bán hiện tại *<input defaultValue="299.000" /></label><label>Giá niêm yết gốc<input defaultValue="350.000" /></label><label>Giá vốn nhập kho<input defaultValue="145.000" /></label></div></div></div><aside className="form-side"><h3>Trạng thái & Hiển thị</h3><p>Trạng thái phát hành</p><label>◉ Đang mở bán</label><label>○ Lưu bản nháp</label><label>○ Ngừng kinh doanh</label><p>Gắn nhãn nổi bật</p><label>Sản phẩm Mới (NEW)　◉</label><label>Sản phẩm Nổi bật　◉</label><h3>Tổng quan kho hàng</h3><div className="stock-preview"><b>8<br/><small>Tổng số SKU</small></b><b>112<br/><small>Tổng hàng tồn</small></b></div></aside><footer><button onClick={onClose}>✕ Hủy bỏ</button><button>Lưu nháp</button><button className="primary-action" onClick={onClose}>Lưu & Xuất bản sản phẩm</button></footer></div> }

function VariantPage() { return <div className="product-screen"><div className="product-breadcrumb">SẢN PHẨM　›　DANH SÁCH SẢN PHẨM　›　QUẢN LÝ BIẾN THỂ</div><div className="product-title"><div><h1>Quản lý biến thể SKU</h1><p>Quản lý màu sắc, kích thước, giá bán và tồn kho theo từng biến thể.</p></div><button className="primary-action">⊕ &nbsp; Thêm biến thể mới</button></div><div className="variant-summary"><h2>Áo Polo Nam Pique Cotton Co Giãn 4 Chiều<br/>FashionStore Signature</h2><Stat label="TỔNG BIẾN THỂ" value="12" unit="3 Màu × 4 Size" color="purple"/><Stat label="TỔNG TỒN KHO" value="185" unit="Đơn vị áo" color="cyan"/><Stat label="ĐÃ BÁN" value="162" unit="Sẵn sàng bán" color="green"/></div><div className="product-filter"><label>⌕ <input placeholder="Tìm theo SKU biến thể hoặc mã vạch GTIN..."/></label><button>Kho Tổng Hà Nội (185)⌄</button><button>Bộ lọc nâng cao</button></div><div className="variant-table"><div className="table-head"><span>□</span><span>ẢNH</span><span>MÃ SKU</span><span>MÀU SẮC</span><span>SIZE</span><span>GIÁ BÁN</span><span>TỒN KHO</span><span>TẠM GIỮ</span><span>TRẠNG THÁI</span></div>{['S','M','L','XL'].map((size, index) => <div className="variant-row" key={size}><span>□</span><div className="tiny-image">P</div><strong>POLO-BLK-{size}</strong><span>● Đen Obsidian</span><b className="size-pill">{size}</b><strong>450.000 đ</strong><b>{24 + index * 11}</b><b className="held">{3 + index}</b><span className="status">• Đang bán</span></div>)}</div></div> }

function AttributePage({ active }: { active: string }) { const isColor = active === 'Màu sắc'; return <div className="product-screen"><div className="product-breadcrumb">THUỘC TÍNH BIẾN THỂ　›　ISO 8601 / VN-GARMENT SPEC</div><div className="product-title"><div><h1>Quản lý Thuộc tính: {isColor ? 'Màu sắc' : 'Kích thước'}</h1><p>Quy chuẩn mã màu và bảng size chart theo chuẩn thời trang quốc tế & form vóc Việt Nam</p></div><button className="primary-action">⊕ &nbsp; Thêm thuộc tính mới</button></div><div className="product-stats"><Stat label={isColor ? 'TỔNG MÃ MÀU CHUẨN' : 'NHÓM KÍCH THƯỚC (SIZE)'} value={isColor ? '24' : '5'} unit={isColor ? 'mã màu sắc' : 'bảng Size Chart'} color="purple"/><Stat label="BIẾN THỂ SKU SỬ DỤNG" value="1.280" unit="SKU" color="green"/><Stat label="HỆ THỐNG CHUYỂN ĐỔI" value="Quốc tế & Form Việt" unit="Fit Guide CSHK Active" color="orange"/></div><div className="attribute-layout"><section className="form-card"><h3>● Bảng {isColor ? 'Mã Màu Sắc (Color Palette)' : 'Kích Thước (Size Chart Management)'}</h3><div className="attribute-grid">{(isColor ? ['Xanh Navy', 'Đen Obsidian', 'Trắng White', 'Nâu Cafe'] : ['Small', 'Medium', 'Large', 'Extra Large']).map((item, index) => <div className="attribute-item" key={item}><i style={{ background: isColor ? ['#1e293b', '#0f172a', '#fff', '#78583f'][index] : '#6366f1' }}/><strong>{item}</strong><small>{isColor ? `#${['1e293b', '0f172a', 'ffffff', '78583f'][index]}` : `SZ-${item.slice(0, 3).toUpperCase()}-P`}</small><b>✎　▣</b></div>)}</div></section><section className="form-card"><h3>Thông số chuẩn: Áo Polo / T-Shirt</h3><table className="size-table"><thead><tr><th>MÃ SIZE</th><th>VÒNG NGỰC</th><th>RỘNG VAI</th><th>DÀI ÁO</th><th>CÂN NẶNG</th></tr></thead><tbody>{['S', 'M', 'L', 'XL'].map((size) => <tr key={size}><td><b className="size-pill">{size}</b></td><td>92 - 96 cm</td><td>42 - 46 cm</td><td>68 - 74 cm</td><td>50 - 77 kg</td></tr>)}</tbody></table></section></div></div> }

function CatalogPage({ title }: { title: string }) { return <div className="product-screen"><div className="product-breadcrumb">SẢN PHẨM　›　{title.toUpperCase()}</div><div className="product-title"><div><h1>Quản lý {title}</h1><p>Quản lý dữ liệu danh mục sản phẩm trong hệ thống FashionStore.</p></div><button className="primary-action">⊕ &nbsp; Thêm mới</button></div><div className="empty-catalog"><b>◫</b><h2>Danh sách {title}</h2><p>Dữ liệu sẽ được tải từ API quản trị tương ứng.</p><button className="primary-action">Thêm bản ghi đầu tiên</button></div></div> }
function Stat({ label, value, unit, color }: { label: string; value: string; unit: string; color: string }) { return <div className={`product-stat ${color}`}><span>{label}</span><strong>{value}</strong><small>{unit}</small></div> }
