import { useEffect, useState } from 'react'
import './warehouse.css'

type Supplier = { MaNhaCungCap: number; TenNhaCungCap: string; NguoiLienHe?: string; SoDienThoai?: string; Email?: string; DiaChi?: string; TrangThai: number }
const API = import.meta.env.VITE_API_URL || 'http://localhost:7000'
const headers = () => ({ 'Content-Type': 'application/json', ...(localStorage.getItem('admin_token') ? { Authorization: `Bearer ${localStorage.getItem('admin_token')}` } : {}) })

export default function SupplierAdminScreen() {
  const [rows, setRows] = useState<Supplier[]>([]); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Supplier | null>(null); const [form, setForm] = useState({ TenNhaCungCap: '', NguoiLienHe: '', SoDienThoai: '', Email: '', DiaChi: '' })
  const load = () => fetch(`${API}/api/nhacungcap`, { headers: headers() }).then((response) => response.ok ? response.json() : null).then((body) => setRows(Array.isArray(body?.data) ? body.data : [])).catch(() => undefined)
  useEffect(() => { void load() }, [])
  const save = async () => { if (!form.TenNhaCungCap.trim()) return; const url = editing ? `${API}/api/nhacungcap/${editing.MaNhaCungCap}` : `${API}/api/nhacungcap`; const response = await fetch(url, { method: editing ? 'PUT' : 'POST', headers: headers(), body: JSON.stringify({ ...form, TrangThai: editing?.TrangThai ?? 1 }) }); if (response.ok) { setEditing(null); setForm({ TenNhaCungCap: '', NguoiLienHe: '', SoDienThoai: '', Email: '', DiaChi: '' }); await load() } }
  const toggle = async (row: Supplier) => { const response = await fetch(`${API}/api/nhacungcap/${row.MaNhaCungCap}`, { method: 'PUT', headers: headers(), body: JSON.stringify({ TrangThai: row.TrangThai ? 0 : 1 }) }); if (response.ok) await load() }
  const filtered = rows.filter((row) => `${row.TenNhaCungCap} ${row.NguoiLienHe || ''} ${row.Email || ''} ${row.DiaChi || ''}`.toLowerCase().includes(query.toLowerCase()))
  return <section className="warehouse-page"><div className="warehouse-heading"><div><small>KHO HÀNG / NHÀ CUNG CẤP</small><h1>Quản lý nhà cung cấp</h1><p>CRUD trực tiếp theo bảng NhaCungCap.</p></div></div><div className="catalog-layout"><div className="catalog-editor"><h2>{editing ? 'Sửa nhà cung cấp' : 'Thêm nhà cung cấp'}</h2>{Object.entries(form).map(([key, value]) => <input key={key} value={value} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={key} />)}{editing && <button className="outline-action" onClick={() => setEditing(null)}>Hủy sửa</button>}<button className="primary-action" onClick={() => void save()}>{editing ? 'Cập nhật' : 'Lưu dữ liệu'}</button></div><div className="warehouse-table-card"><div className="warehouse-filters"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm nhà cung cấp..." /></div><table className="warehouse-table"><thead><tr><th>ID</th><th>Nhà cung cấp</th><th>Liên hệ</th><th>Địa chỉ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.MaNhaCungCap}><td>#{row.MaNhaCungCap}</td><td>{row.TenNhaCungCap}</td><td>{row.NguoiLienHe || '-'}<br />{row.Email || row.SoDienThoai || '-'}</td><td>{row.DiaChi || '-'}</td><td>{row.TrangThai ? 'Hoạt động' : 'Tạm dừng'}</td><td><button className="table-action" onClick={() => { setEditing(row); setForm({ TenNhaCungCap: row.TenNhaCungCap, NguoiLienHe: row.NguoiLienHe || '', SoDienThoai: row.SoDienThoai || '', Email: row.Email || '', DiaChi: row.DiaChi || '' }) }}>Sửa</button><button className="table-action" onClick={() => void toggle(row)}>{row.TrangThai ? 'Tắt' : 'Bật'}</button></td></tr>)}</tbody></table></div></div></section>
}
